version: '3'
services:
  jinux:
    image: ${DOCKER_USER_ID}/jinux-assignment4:latest
    container_name: jinux
    
    build:
       context: .
       
    restart: always
    ports:
      - 80:80

